### ISSUE TITLE
too dumb exception 报错

### ISSUE THREAD

**Issue by zihaowu-hirain** [vortezwohl/CEO-Agentic-AI-Framework#18]
Traceback (most recent call last):
  File "D:\project\CEO\demo\math_calc_and_file_access.py", line 3, in <module>
    from ceo import (
  File "D:\project\CEO\ceo\__init__.py", line 3, in <module>
    from .brain.agent import Agent
  File "D:\project\CEO\ceo\brain\agent.py", line 10, in <module>
    from ceo.ability.agentic_ability import PREFIX as AGENTIC_ABILITY_PREFIX
  File "D:\project\CEO\ceo\ability\__init__.py", line 2, in <module>
    from .agentic_ability import AgenticAbility
  File "D:\project\CEO\ceo\ability\agentic_ability.py", line 5, in <module>
    from ceo.brain.base_agent import BaseAgent
  File "D:\project\CEO\ceo\brain\base_agent.py", line 8, in <module>
    from ceo.prompt import (
  File "D:\project\CEO\ceo\prompt\__init__.py", line 9, in <module>
    from .next_move_prompt import NextMovePrompt
  File "D:\project\CEO\ceo\prompt\next_move_prompt.py", line 8, in <module>
    from ceo.exception.too_dumb_exception import TooDumbException
  File "D:\project\CEO\ceo\exception\too_dumb_exception.py", line 7
    super().__init__(f'The model "{model.dict()['model_name']}" is too dumb to be my brain, '
                                                 ^^^^^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by vortezwohl** [comment]
solved
